version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Skillup@490
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

  skillup_api:
    build:
      context: ./SkillUp_BE/SkillUp
      dockerfile: Dockerfile
    container_name: skillup_api
    depends_on:
      - mssql
    ports:
      - "5120:5120"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=SkillUp;User Id=sa;Password=Skillup@490;TrustServerCertificate=True;
    restart: unless-stopped

  gensub:
    build:
      context: ./SkillUp_Py
      dockerfile: Dockerfile
    container_name: gensub
    ports:
      - "8000:8000"
    volumes:
      - ./SkillUp_Py/upload:/app/upload
      - ./SkillUp_Py/logs:/app/logs
    environment:
      - BEAM_SIZE=${BEAM_SIZE:-1}
      - BEST_OF=${BEST_OF:-1}
      - VAD_MIN_SIL_MS=${VAD_MIN_SIL_MS:-300}
      - PARALLEL_PROCESSING_ENABLED=${PARALLEL_PROCESSING_ENABLED:-1}
      - PARALLEL_CHUNK_DURATION=${PARALLEL_CHUNK_DURATION:-90.0}
      - PARALLEL_MIN_DURATION=${PARALLEL_MIN_DURATION:-180.0}
      - PARALLEL_MAX_WORKERS=${PARALLEL_MAX_WORKERS:-2}
      - ALLOWED_REMOTE_VIDEO_HOSTS=api.skillup.website,222.255.214.208
    restart: unless-stopped

volumes:
  mssql_data: