# Docker Compose file version
version: '3.8'

services:
  # SQL Server Database Service
  db:
    # Sử dụng custom image từ Docker Hub (đã bao gồm init scripts)
    image: "quatbt/skillup-mssql:latest"

    # Để build từ Dockerfile local thay vì pull từ Docker Hub, comment dòng trên và uncomment dòng dưới:
    # build:
    #   context: .
    #   dockerfile: Dockerfile

    # Tự động khởi động lại container khi bị dừng hoặc crash
    restart: always

    # Đặt tên container để dễ quản lý
    container_name: mssqlserver

    # Các biến môi trường cấu hình SQL Server
    environment:
      # Mật khẩu cho tài khoản SA (System Administrator) - lấy từ file .env
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}

      # Chấp nhận điều khoản sử dụng của Microsoft (bắt buộc)
      ACCEPT_EULA: "Y"

      # Phiên bản SQL Server (Express: miễn phí, phù hợp cho development)
      MSSQL_PID: "Express"

    # Mapping port: host:container
    # Port 1435 trên máy host sẽ map tới port 1433 trong container
    ports:
      - "${MSSQL_PORT}:1433"

    # Volumes để lưu trữ dữ liệu persistent
    volumes:
      # Volume lưu trữ database data - giữ dữ liệu khi container restart
      - sqlserver_data:/var/opt/mssql

      # Mount folder init-scripts để chạy các script khởi tạo database
      - ./init-scripts:/docker-entrypoint-initdb.d

      # Mount folder backups để lưu trữ các file backup database
      - ./backups:/var/backups

    # Kết nối container vào network để có thể giao tiếp với các service khác
    networks:
      - skillup-network

    # Health check để kiểm tra trạng thái container
    healthcheck:
      # Lệnh kiểm tra: thử kết nối và query database
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -Q 'SELECT 1' || exit 1" ]

      # Kiểm tra mỗi 10 giây
      interval: 10s

      # Thử lại tối đa 10 lần nếu thất bại
      retries: 10

      # Thời gian chờ trước khi bắt đầu health check (container cần thời gian khởi động)
      start_period: 10s

      # Timeout cho mỗi lần check
      timeout: 3s

# Định nghĩa volumes
volumes:
  # Volume lưu trữ dữ liệu SQL Server (persistent storage)
  sqlserver_data:
    driver: local

# Định nghĩa networks
networks:
  # Network bridge để các container có thể giao tiếp với nhau
  skillup-network:
    driver: bridge
